# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56dfcb52ede380b35afce48f17473404fa7d0dc7bd2bd11663e70011403f1e76a44975355daac70a2e9db0a26862ef6eaba5731e9f6cb5cc1ffccc4ed45afb07

test:
  secret_key_base: c3370d07e70477348b8c6dc71f9a80c7f688c4aa2d998a8b3fb4d971544651bc2004f2796b5358b4b5d590a976cfa9d614e09cdb80a9f29ede640da95eb61d6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
